### PR TITLE
Rename instancing -> ambient_example_instancing

### PR DESCRIPTION
**Pull request by pierd**
... to match other examples

### CODE REVIEW

**Comment by ten3roberts** [comment]
Great.

I just used `ambient new ./guest/rust/examples/basic/instancing` to create it.

Is there another preferred way to create our own examples that I've missed?

**Review by ten3roberts — APPROVED** [review]
Works on my end and branch 👍

**Comment by pierd** [comment]
I don't think that we have a process for adding examples (yet). I'm assuming that the directory names for examples are shortened just like for our crates (`ambient_network` crate in `network` dir).

I've only noticed because I've added a GitHub action for deploying all examples weekly.

**Comment by pierd** [comment]
BTW this example is quite trippy 😵‍💫 🤣

**Comment by ten3roberts** [comment]
I've discovered an overrun write in our culling and collect compute shader that *only* occurs on the web, so this is a smaller reproduction of it. Discovered a quite massive overcommit in the culling.

**Comment by ten3roberts** [comment]
The samplers example have failed locally for me before. Hopefully it is just flaky

**Pull request merged**
