### PR TITLE
Rename screen_ray to clip_space_ray

### PR DESCRIPTION
**Pull request by owenpalmer**
Fixes a task in this comment https://github.com/AmbientRun/Ambient/issues/283#issuecomment-1513477893

### CODE REVIEW

**Comment by owenpalmer** [comment]
@philpax Looks like they failed due to a problem with the action. Same thing happened here https://github.com/AmbientRun/Ambient/pull/329

**Comment by philpax** [comment]
Awesome! Do you think you'd be able to add some text on top of where your cursor is to the `screen_ray` example? Should be able to create a `Text.el()` that updates its `translation` each frame (using the `use_frame` hook)

**Comment by owenpalmer** [comment]
What's the best way to mutate the text Element's translation component from inside `use_frame`? I'm currently a little unfamiliar with the UI API. Thx :)

**Comment by philpax** [comment]
Hm, just realised that's not a simple suggestion because you'll need a way to get the world position back from the server. OK, ignore that for now and I'll add it once I do some other work. Is the PR good to go otherwise?

**Comment by philpax** [comment]
Ended up doing the UI stuff because I realised we didn't have `use_module_message`. If you're okay with everything, I'll merge 🚀

**Comment by owenpalmer** [comment]
Cool, yep everything looks good to me! Thanks for doing that UI stuff :)

**Pull request merged**
