### PR TITLE
feat(campfire): replace OpenSSL with Rust deps

### PR DESCRIPTION
**Pull request by philpax**
Really didn't want to go through the hassle of getting OpenSSL to work on Windows, so I just replaced the logic with Rust equivalents. My Chrome starts up and connects to my 127.0.0.1 server OK. Need to test on the other platforms.

### CODE REVIEW

**Comment by ten3roberts** [comment]
What happened here?

https://tenor.com/view/antman-what-the-hell-happened-here-avengers-gif-18240147

Line ending shenanigans?

**Comment by philpax** [comment]
> What happened here?
> 
> https://tenor.com/view/antman-what-the-hell-happened-here-avengers-gif-18240147
> 
> Line ending shenanigans?

You didn't see anything 🙈

**Review by ten3roberts — APPROVED** [review]
Works well on Mac as well.

Good job, am not that familiar with certificate things like x509, so I just used what openssl provided.

I've learnt a ton, thanks

**Comment by philpax** [comment]
Yeah, no worries at all, the cert stuff can be quite scary. I worked for a 2FA startup as my first job, so I ended up learning a lot about certificates and crypto and enough to know I should leave it to the experts for the most part 😂

**Pull request merged**
