### PR TITLE
Removing wasmtime's cache feature also removes the dependency on zstd which has a significant effect on compile times.

### PR DESCRIPTION
**Pull request by Pombal**

### CODE REVIEW

**Comment by ten3roberts** [comment]
This will likely conflict with #661 as it changes the wasmtime dependency altogether and no longer uses it

**Review by philpax — APPROVED** [review]
TIL about `cache`. It would be nice to get that working at some point to avoid the JIT compilation hit if you're launching the same modules again, but it seems underdocumented so I'm guessing it's not really there yet. LGTM otherwise.

**Comment by Pombal** [comment]
@ten3roberts Are you ok with this change landing and resolving the conflict once client-wasm in merged?

**Comment by ten3roberts** [comment]
Yes, I can resolve the merge conflict absollutely. It'll just unfortunately noop when my branch is merged and we will have to add it to `wasm-bridge` instead, but I'll migrate the side effects of this change over 😊

**Pull request merged**
