### PR TITLE
fix(web): semantic packages

### PR DESCRIPTION
**Pull request by ten3roberts**
Fixes `Error: no such component: 336` seen on the web client

### CODE REVIEW

**Comment by ten3roberts** [comment]
image

**Review by philpax — APPROVED** [review]
It would be ideal to share the component inits between the clients, but this is fine for now

**Comment by ten3roberts** [comment]
> It would be ideal to share the component inits between the clients, but this is fine for now

Yes. I am working on that now, as all the component inits uses libraries which are either currently not supported on wasm, or never will be, such as physics

**Comment by ten3roberts** [comment]
Golden images and the failing examples all work locally (Mac Mini S2)

**Pull request merged**
