### PR TITLE
Clean up deploy output

### PR DESCRIPTION
**Pull request by FredrikNoren**
Just show the url that the user can click

### CODE REVIEW

**Comment by philpax** [comment]
Not opposed in theory, but can we show the server URL on the website (not necessarily the deploy output) so that someone who can't use the web client can join natively?

i.e. I'm making a game and want to share it with my Linux-using friend who has Ambient installed (and our current target audience has a not-insignificant Linux userbase) - how do they join my deployed game?

**Comment by FredrikNoren** [comment]
@philpax To share with friends that can't use the web client I would still recommend people to use the "download native" button on the website. It's the only reliable way to share it right now. Using `ambient join` if you have it installed won't work reliably since the version may mismatch.

**Comment by philpax** [comment]
> @philpax To share with friends that can't use the web client I would still recommend people to use the "download native" button on the website. It's the only reliable way to share it right now. Using `ambient join` if you have it installed won't work reliably since the version may mismatch.

But that won't necessarily join them to the same server, and we're likely to have a userbase of dev-users who already have Ambient 0.3 launched - that is, people sharing their games with each other.

Joining with the wrong version will fail, so I think it's safe to expose that, even with that risk in mind.

**Comment by FredrikNoren** [comment]
@philpax Alright

**Pull request merged**
