### PR TITLE
Expose inactivity shutdown

### PR DESCRIPTION
**Pull request by pierd**
I've noticed that we already have one. Fixing it and exposing as an argument so that it can be easily used on the backend.

### CODE REVIEW

**Review by philpax — COMMENTED** [review]
What's the reason for exposing the join handle from the server?

**Comment by pierd** [comment]
> What's the reason for exposing the join handle from the server?

We spawn the server in a separate task so we have to wait on something. For `run` it blocks on client, for `serve` we just waited for ctrl+c no matter what is happening to the server. For the process to actually end when the server ends I have to wait on its task directly.

**Comment by pierd** [comment]
@philpax what do you think about using an explicit struct instead of a tuple? For example `ServerHandle`?

**Comment by philpax** [comment]
Sounds good to me!

**Pull request merged**
