### PR TITLE
Support running with URL as project path

### PR DESCRIPTION
**Pull request by pierd**
One of the requirements for [deployment](https://github.com/AmbientRun/InternalIssues/issues/15) is being able to run ambient project (`run`/`serve`) with an URL.

### CODE REVIEW

**Review by FredrikNoren — APPROVED** [review]
Ohhh, niice! Just skimmed the code but seems reasonable to me

**Review by philpax — APPROVED** [review]
Also skimmed over it, looks good! It looks like the `metadata` might also be the start of #349 ?

**Comment by ten3roberts** [comment]
So if I've understood it this allows using an already running url as the "file server" for the project files, while the local command only does the computing?

Perhaps we should mention this in the book that it is possible to point the project to an url, similar to how vim allows ssh paths.

**Comment by pierd** [comment]
> So if I've understood it this allows using an already running url as the "file server" for the project files, while the local command only does the computing?
> 
> Perhaps we should mention this in the book that it is possible to point the project to an url, similar to how vim allows ssh paths.

Yes, like a read-only file server for the built project files.

**Pull request merged**
