### PR TITLE
Fix disconnecting before entering the name in AFPS

### PR DESCRIPTION
**Pull request by pierd**

### CODE REVIEW

**Comment by pierd** [comment]
FYI @chaosprint

**Review by philpax — APPROVED** [review]
I was confused at first, but then I remembered `wait_for_component` will *also* return if the entity was deleted. Maybe we should make that more obvious somehow.

**Comment by pierd** [comment]
> I was confused at first, but then I remembered `wait_for_component` will _also_ return if the entity was deleted. Maybe we should make that more obvious somehow.

A bit heavy handed but we could add `#[must_use]` to `wait_for_component`.

**Comment by philpax** [comment]
> > I was confused at first, but then I remembered `wait_for_component` will _also_ return if the entity was deleted. Maybe we should make that more obvious somehow.
> 
> A bit heavy handed but we could add `#[must_use]` to `wait_for_component`.

You know that's not actually a bad idea, I'll do that

**Pull request merged**
